version: "3.7"
services:
    app:
        build:
            args:
                user: vovan4a
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: money
        container_name: money-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - money
    db:
        image: mysql:5.7
        container_name: money-db
        restart: unless-stopped
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ./docker-compose/mysql:/docker-entrypoint-initdb.d
        networks:
            - money
    nginx:
        image: nginx:1.17-alpine
        container_name: money-nginx
        restart: unless-stopped
        ports:
            - 8000:80
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d
        networks:
            - money

networks:
    money:
        driver: bridge


# увидел такой вариант - проверить заменив более новыми версиями!
#    version: '2'
#    services:
#        nginx:
#            image: jboesl/docker-nginx-headers-more
#            ports:
#                - "80:80"
#                - "443:443"
#            volumes:
#                - ./:/site
#                - ./docker/nginx:/etc/nginx/conf.d
#            depends_on:
#                - fpm
#            links:
#                - fpm
#        fpm:
#            build: ./docker/php
#            expose:
#                - "9000"
#            volumes:
#                - ./:/site
#            links:
#                - mysql
#        mysql:
#            image: mysql
#            ports:
#                - "3306:3306"
#            environment:
#                MYSQL_ROOT_PASSWORD: "root"
#                MYSQL_DATABASE: "portal"
#                MYSQL_USER: "app"
#                MYSQL_PASSWORD: "app"
#            volumes:
#                - mysqldata:/var/lib/mysql
#    volumes:
#        mysqldata:
#            driver: "local"
